apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fe
spec:
  replicas: 1
  selector: # deployment-pod 대응
    matchLabels:
      app: fe
  template: # pod 템플릿
    metadata:
      labels:
        app: fe # pod의 라벨
    spec:
      containers:
        - name: pod-fe
          image: yuje123/fe:0.4
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL # 컨테이너 환경변수명
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: react_app_api_url
