apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  selector:
    app: fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe
  template: # pod 템플릿
    metadata:
      labels:
        app: fe # pod의 라벨
    spec:
      containers:
        - name: fe
          image: yuje123/fe:0.5
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL # 컨테이너 환경변수명
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: react_app_api_url
