apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: frontend
  template: # pod 템플릿
    metadata:
      labels:
        app: frontend # pod의 라벨
    spec:
      containers:
        - name: frontend
          image: yuje123/fe:0.6
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL # 컨테이너 환경변수명
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: react_app_api_url
