apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemo-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nemo-react
  template: # pod 템플릿
    metadata:
      labels:
        app: nemo-react # pod의 라벨
    spec:
      containers:
        - name: nemo-react
          image: yuje123/fe:0.6
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL # 컨테이너 환경변수명
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REACT_APP_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: nemo-react
spec:
  type: LoadBalancer
  selector:
    app: nemo-react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

