apiVersion: v1
kind: Pod
metadata:
  name: pod-fe
spec:
  containers:
    - name: pod-fe
      image: yuje123/test:0.1
      ports:
        - containerPort: 3000
      # readinessProbe:
      #   httpGet:
      #     path: /
      #     port: 3000
      #   initialDelaySeconds: 10
      #   periodSeconds: 10
      # livenessProbe:
      #   httpGet:
      #     path: /
      #     port: 3000
      #   initialDelaySeconds: 5
      #   periodSeconds: 5
      env:
        - name: REACT_APP_API_URL # 컨테이너 환경변수명
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: react_app_api_url
