apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  selector:
    app: fe
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
# type external
# autoscaling 도입
